#!/usr/bin/env python3
"""Discover consumers of KDH plan index files.

This is the repo-relative replacement for the old PHX v4 scaffold that scanned
hard-coded home directories. It answers one narrow governance question:

  Which active pipeline/skill files mention the plan index, and do they read,
  write, or both?

Defaults intentionally ignore archives and generated output so stale history
does not masquerade as live workflow wiring.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from dataclasses import dataclass, asdict
from pathlib import Path


DEFAULT_INCLUDES = (
    "skills/**/SKILL.md",
    "scripts/**/*.py",
    "scripts/**/*.sh",
    "hooks/**/*",
    ".claude/hooks/**/*",
    "README.md",
)

EXCLUDED_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    "__pycache__",
    "archive",
    "_archive",
    "_bmad-output",
    "node_modules",
}

SEARCH_PATTERNS = (
    re.compile(r"_bmad-output/kdh-plans/_index\.yaml"),
    re.compile(r"_bmad-output/_index\.yaml"),
    re.compile(r"kdh-plans/_index"),
)

WRITE_HINTS = (
    re.compile(r"\bwrite_text\s*\("),
    re.compile(r"\byaml\.safe_dump\b"),
    re.compile(r"\bjson\.dump\b"),
    re.compile(r"\bopen\s*\([^)]*['\"](?:w|a|r\+)['\"]"),
    re.compile(r"\btee\s+[^|;]*_index\.yaml"),
    re.compile(r">>?\s*[^|;]*_index\.yaml"),
    re.compile(r"\bsed\s+-i\b"),
    re.compile(r"(?:update|append|write|mutat|flip|register|등재|업데이트|수정|생성)", re.IGNORECASE),
)

READ_HINTS = (
    re.compile(r"\bread_text\s*\("),
    re.compile(r"\byaml\.safe_load\b"),
    re.compile(r"\bjson\.load\b"),
    re.compile(r"\bopen\s*\([^)]*['\"]r['\"]"),
    re.compile(r"\bcat\s+[^|;]*_index\.yaml"),
    re.compile(r"\bgrep\s+[^|;]*_index\.yaml"),
    re.compile(r"(?:read|load|inspect|check|확인|읽기|조회)", re.IGNORECASE),
)


@dataclass(frozen=True)
class Consumer:
    path: str
    role: str
    hits: int
    matched_terms: list[str]


def is_excluded(path: Path, repo_root: Path) -> bool:
    try:
        rel = path.relative_to(repo_root)
    except ValueError:
        rel = path
    return bool(set(rel.parts) & EXCLUDED_PARTS)


def strip_comments(text: str, suffix: str) -> str:
    if suffix in {".py", ".sh"}:
        return "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("#"))
    if suffix in {".js", ".ts"}:
        return "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("//"))
    return text


def classify(text: str) -> str:
    writes = any(pattern.search(text) for pattern in WRITE_HINTS)
    reads = any(pattern.search(text) for pattern in READ_HINTS)
    if writes and reads:
        return "B"
    if writes:
        return "W"
    return "R"


def discover(repo_root: Path, includes: list[str]) -> list[Consumer]:
    repo_root = repo_root.resolve()
    found: dict[str, Consumer] = {}

    for pattern in includes:
        for path in repo_root.glob(pattern):
            if not path.is_file() or is_excluded(path, repo_root):
                continue
            try:
                raw = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            scrubbed = strip_comments(raw, path.suffix)
            matched: list[str] = []
            hits = 0
            for search_pattern in SEARCH_PATTERNS:
                matches = search_pattern.findall(scrubbed)
                if matches:
                    matched.append(search_pattern.pattern)
                    hits += len(matches)
            if not hits:
                continue
            rel = path.relative_to(repo_root).as_posix()
            found[rel] = Consumer(path=rel, role=classify(scrubbed), hits=hits, matched_terms=matched)

    return sorted(found.values(), key=lambda item: item.path)


def emit_yaml(consumers: list[Consumer], repo_root: Path) -> str:
    lines = [
        "# generated by scripts/discover-plan-index-consumers.py",
        "version: 1",
        f"repo_root: {repo_root.resolve().as_posix()}",
        f"total: {len(consumers)}",
        "consumers:",
    ]
    for consumer in consumers:
        lines.append(f"  - path: {consumer.path}")
        lines.append(f"    role: {consumer.role}")
        lines.append(f"    hits: {consumer.hits}")
        lines.append("    matched_terms:")
        for term in consumer.matched_terms:
            lines.append(f"      - {term}")
    return "\n".join(lines) + "\n"


def run_self_test() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "skills" / "reader").mkdir(parents=True)
        (root / "skills" / "writer").mkdir(parents=True)
        (root / "archive" / "old").mkdir(parents=True)
        (root / "scripts").mkdir()

        (root / "skills" / "reader" / "SKILL.md").write_text(
            "Read _bmad-output/kdh-plans/_index.yaml before work.\n",
            encoding="utf-8",
        )
        (root / "skills" / "writer" / "SKILL.md").write_text(
            "Update _bmad-output/_index.yaml after publishing.\n",
            encoding="utf-8",
        )
        (root / "scripts" / "both.py").write_text(
            "p = '_bmad-output/kdh-plans/_index.yaml'\n"
            "data = path.read_text()\n"
            "path.write_text(data)\n",
            encoding="utf-8",
        )
        (root / "archive" / "old" / "SKILL.md").write_text(
            "Read _bmad-output/kdh-plans/_index.yaml\n",
            encoding="utf-8",
        )

        consumers = discover(root, list(DEFAULT_INCLUDES))
        got = {(c.path, c.role) for c in consumers}
        expected = {
            ("skills/reader/SKILL.md", "R"),
            ("skills/writer/SKILL.md", "W"),
            ("scripts/both.py", "B"),
        }
        if got != expected:
            print(json.dumps({"verdict": "FAIL", "expected": sorted(expected), "got": sorted(got)}, indent=2), file=sys.stderr)
            return 1
    print("PASS: discover-plan-index-consumers self-test")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=".", type=Path)
    parser.add_argument("--include", action="append", help="glob relative to repo root; repeatable")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--fail-on-empty", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv)

    if args.self_test:
        return run_self_test()

    includes = args.include if args.include else list(DEFAULT_INCLUDES)
    consumers = discover(args.repo_root, includes)
    if args.fail_on_empty and not consumers:
        print("FAIL: no plan index consumers found", file=sys.stderr)
        return 1

    if args.json:
        payload = {
            "version": 1,
            "repo_root": args.repo_root.resolve().as_posix(),
            "total": len(consumers),
            "consumers": [asdict(consumer) for consumer in consumers],
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        print(emit_yaml(consumers, args.repo_root), end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
